class_12/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :presidents

end

class_12/app/models/president.rb
class President < ActiveRecord::Base
end

class_12/app/controllers/home_controller.rb
class HomeController < ApplicationController
  # respond_to :html

  def index
    @presidents = President.all
    # respond_with @presidents
  end
  
end

class_12/app/controllers/presidents_controller.rb
class PresidentsController < ApplicationController

  # def index
  #   # GET
  #   # List of data
  #   # Replaced by our home index CURRENTLY
  # end

  def show
    # GET
    # Shows an individual object
    @president = President.find params[:id]
  end

  def new
    # GET
    # Brings you to the new page
    @president = President.new
  end

  def create
    # POST
    # Creates the data
    @president = President.create president_params
    redirect_to root_path
  end

  def edit
    # GET
    # Brings you to the edit page
    @president = President.find params[:id]
  end

  def update
    # PUT/PATCH
    # Updates existing data
    @president = President.find params[:id]
    @president.update_attributes president_params
    redirect_to root_path
  end

  def destroy
    # DELETE
    # Deletes stuff
    @president = President.find params[:id]
    @president.delete
    redirect_to root_path
  end


  private
    def president_params
      params.require(:president).permit(:name, :terms, :borndate)
    end

end

class_12/app/helpers/presidents_helper.rb
module PresidentsHelper
end

class_12/app/views/home/index.html.erb
<h3>My Presidents</h3>

<%= link_to "Create New President", new_president_path %>
<ul>
  <% @presidents.each do |pres| %>
    <li>
      <%= pres.name %> &nbsp;

      <%= link_to "Show", president_path(pres) %>
      <%= link_to "Edit", edit_president_path(pres) %>
      <%= link_to "Delete", president_path(pres), method: :delete %>


    </li>  
  <% end %>
</ul>

class_12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Class12</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>