homeworks/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get '/newgame' => 'home#newgame'

  resources :users

  resources :courses

  resources :locations

  resources :assignments

  

end

homeworks/app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :course
	belongs_to :user
	has_many :submissions
	has_many :comments, as: :commentable

end

homeworks/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

homeworks/app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :location

	has_many :coursejoins
	has_many :users, through: :coursejoins

	has_many :assignments


end

homeworks/app/models/coursejoin.rb
class Coursejoin < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
end

homeworks/app/models/location.rb
class Location < ActiveRecord::Base
	has_many :courses 
end

homeworks/app/models/submission.rb
class Submission < ActiveRecord::Base
	belongs_to :assignment
	belongs_to :user
	has_many :comments, as: :commentable
end

homeworks/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :coursejoins
  has_many :courses, through: :coursejoins

  has_many :assignments
  has_many :submissions
end

homeworks/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :authenticate_user! 

	def new
		# @location = Location.find params[:location_id]
		@location_id = params[:location_id]
		# @course = @location.courses.new
		@course = Course.new
	end

	def create		
		@location = Location.find params[:course][:location_id]

		@course = @location.courses.new course_params
		@course.save
		redirect_to location_path(@location)
	end

	def show
		@course = Course.find params[:id]

	end

	private 

	def course_params
    	params.require(:course).permit(:name)
    end


end

homeworks/app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user! 

	def index
	end

	# def newgame
	# 	# Put all the cards into the array
	# 	@deck = [
	# 		"7clubs", "7diamonds", "7spades", "7hearts",
	# 		"8clubs", "8diamonds", "8spades", "8hearts",
	# 		"9clubs", "9diamonds", "9spades", "9hearts",
	# 		"10clubs", "10diamonds", "10spades", "10hearts",
	# 		"Jclubs", "Jdiamonds", "Jspades", "Jhearts",
	# 		"Qclubs", "Qdiamonds", "Qspades", "Qhearts",
	# 		"Kclubs", "Kdiamonds", "Kspades", "Khearts",
	# 		"Aclubs", "Adiamonds", "Aspades", "Ahearts"
	# 	]
	# 	@deck.shuffle!
	# 	render 'index'

	# end
end

homeworks/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :authenticate_user! 

	def index
		@locations = Location.all
	end

	def new
		@location = Location.new
	end

	def create
		@location = Location.new location_params
		@location.save
		redirect_to locations_path
	end

	def show
		@location = Location.find params[:id]		
	end

	def edit
	end

	def update
	end

	def destroy
	end


	private 

	def location_params
    	params.require(:location).permit(:name)
    end


end

homeworks/app/controllers/users_controller.rb
class UsersController < ApplicationController
end

homeworks/app/helpers/courses_helper.rb
module CoursesHelper
end

homeworks/app/helpers/locations_helper.rb
module LocationsHelper
end

homeworks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Wilson Assignment Tracker</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- <link href="starter-template.css" rel="stylesheet"> -->

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Assignment Tracker</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="logoutbuttondiv">
        <ul class="hmenu">
        <%= render 'devise/menu/login_items' %>
        </ul>
      </div>

      <div class="starter-template">
        <h1>Wilson Assignment Tracker</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

      <%= yield %>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script -->
    <!-- script src="../../dist/js/bootstrap.min.js"></script -->
  </body>
</html>

homeworks/app/views/locations/index.html.haml
%h3 Locations

&nbsp;&nbsp;
= link_to "(Add Location)", new_location_path

%ul
- @locations.each do |loc|
	%li
		= link_to "#{loc.name}", location_path(loc)

homeworks/app/views/locations/new.html.haml
= simple_form_for @location do |f|
	= f.input :name, label: "Location name", input_html: { maxlength: 20 }
	= f.button :submit
	
	/ = button_tag "Cancel", :type => 'reset'
	%a{:href => locations_path}
		%input{type: "button", value: "Cancel"}/
	

homeworks/app/views/locations/show.html.haml
/ SHOW a single location
%h3
	Location: &nbsp;
	= @location.name

%h4 Courses:
&nbsp;&nbsp;
= link_to "(Add Course)", new_course_path(location_id: @location.id)	

%ul
- @location.courses.each do |course|
	%li
		= link_to "#{course.name}", course_path(course)	